### ISSUE TITLE
How to use Blade in Sitecore 7.0

### ISSUE THREAD

**Issue by quachnguyen** [kamsar/Blade#6]
Hello kamsar,

I'm new in Blade, I setup and apply the layout but it didn't display as I expect, even it didn't step into SamplePresenter file, I guess that I miss something in configuration.

Please see the attachment
![image](https://cloud.githubusercontent.com/assets/128512/9002905/51514ade-3793-11e5-9ce9-9fb9ce27af88.png)

**Comment by kamsar** [comment]
Is your presenter `IPresenter<SampleModel>` (or `SitecorePresenter<SampleModel>`)?

If so the next step is to review the presenter factory.

Note, however that Blade is deprecated and I recommend using native Sitecore MVC instead. Prior to 7.2-ish, Sitecore MVC was notably substandard compared to webforms support (and that was the reason for Blade), but that is no longer the case.

**Comment by quachnguyen** [comment]
Hello Kamsar,

Thanks for your response, actually I'm using the default Sample Razor Rendering when I installed Blade's sample. 

Here is my step:

1. Install Synthesis, Blade and Blade's Sample
2. Then I create Layout Rendering and map sample *.cshtml and Model. (see attachment)
3. Set the layout for Home item.

- Review home page, even the visual studio's debugger didn't step into SamplePresenter.cs file. But the model is empty if I debug into Sample Razor Rendering.cshtml file

![sample razor](https://cloud.githubusercontent.com/assets/128512/9030273/886d2aa4-39ca-11e5-8ac0-daf3329183e7.png)

Please help me solved it
Thanks

**Comment by kamsar** [comment]
Ah I see the confusion here. You cannot use cshtml layouts with Blade, only renderings. As soon as Sitecore sees a cshtml layout it activates Sitecore MVC.

**Comment by quachnguyen** [comment]
Thanks Kamsar so much for your time
